@startuml

title Architecture
skinparam object {
          BackgroundColor Snow
          BorderColor Green
          ArrowColor Green
}
skinparam defaultTextAlignment center

'COMMON
package "Common" {
  node Authentification
  node Configuration
  node Logging
  node Flaggr
}


'PRESENTATION (Android Part)
package "Presentation" {
  node "Application"
  node "Di"
  node "Views"
  node "Extensions"
   node ViewModels
}

'DOMAIN MODEL
package "Domain-Models" {
  () Team
  () Tournament
  () Club
  () Manche
  () Phase
}

'DATAS
package "Data" {
'LOCAL MODULE
rectangle "LocalModule" {
  node repositoriesLocal {
    () TeamLocalDataSourceRepo
  }

    node localMapper
  node contractsLocal {
    () TeamLocalDataSourceContract
  }
}

TeamLocalDataSourceRepo .up.> TeamLocalDataSourceContract #Red

'EXTERNAL MODULE
rectangle "ExternalModule" {
  node apis {
    () TeamService
  }
  node externalMapper
  node repositoriesExternal {
      () TeamExternalDataSourceRepo
    }

    node contractsExternal {
      () TeamExternalDataSourceContract
    }
}
TeamExternalDataSourceRepo .up.> TeamExternalDataSourceContract #Red

}

'DOMAIN USE CASES
package "Domain" {
    node contracts {
        () TeamDataSourceContract
    }
    node repositories{
        () TeamRepo
    }

  node contractsDomain {
      () TeamContract
    }

  node UseCases {
    () getTeamsUseCase
  }
}
TeamRepo .up.> TeamDataSourceContract #Red
getTeamsUseCase .up.> TeamContract #Red


'EXTERNAL DATA SOURCE
rectangle API

database "MySql" {
  rectangle TeamDB
  rectangle TournamentDB
}

'RELATIONS
Views -down--> ViewModels
ViewModels .down.> Team #blue
ViewModels -right-> getTeamsUseCase
getTeamsUseCase -right-> TeamRepo

TeamRepo --> localMapper
localMapper-down-> TeamLocalDataSourceRepo

TeamRepo --> externalMapper
externalMapper --> TeamExternalDataSourceRepo
TeamExternalDataSourceRepo --> TeamService
TeamService -down-> API
API --> TeamDB


'Come back
TeamLocalDataSourceRepo --> localMapper #purple
localMapper --> TeamRepo #purple
TeamExternalDataSourceRepo --> externalMapper #purple
externalMapper --> TeamRepo #purple
TeamService --> TeamExternalDataSourceRepo #purple

TeamRepo -left-> getTeamsUseCase #purple


Views ..> Team #blue
Views ..> Club #blue

'Hidden relations
TeamExternalDataSourceRepo -[hidden]down- TeamService
UseCases -[hidden]- externalMapper

@enduml